version: '3'

services:
  consul-agent-1: &consul-agent
    image: consul:latest
    networks:
      - consul-demo
    environment: 
      - CONSUL_BIND_INTERFACE=eth0
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-bootstrap:
    <<: *consul-agent
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"    
    command: "agent -dev -client 0.0.0.0"

networks:
  consul-demo: